# Generated by Django 5.0.13 on 2025-04-29 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='day_clean',
        ),
    ]
