# Generated by Django 5.0.14 on 2025-05-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_manager', '0002_remove_sensor_day_clean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='expiry_date',
        ),
    ]
