# Generated by Django 5.0.13 on 2025-04-25 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_environment', '0002_alter_transaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='monitor_environment.station'),
            preserve_default=False,
        ),
    ]
