# Generated by Django 5.0.13 on 2025-04-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_environment', '0003_parameter_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='caution_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='caution_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='danger_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='danger_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='normal_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='normal_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
