# Generated by Django 5.0.13 on 2025-04-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_environment', '0004_parameter_caution_max_parameter_caution_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
