# Generated by Django 5.0.13 on 2025-04-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_environment', '0005_sensor_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='time',
            new_name='expiry_date',
        ),
    ]
