# Generated by Django 5.0.13 on 2025-04-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_environment', '0006_rename_time_sensor_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='plant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='monitor_environment.plant'),
            preserve_default=False,
        ),
    ]
