# Generated by Django 5.0.13 on 2025-04-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_environment', '0007_sensor_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='day_clean',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
