# Generated by Django 5.0.13 on 2025-04-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_environment', '0008_sensor_day_clean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='day_clean',
            field=models.DateField(blank=True, null=True),
        ),
    ]
