# Generated by Django 5.0.14 on 2025-04-27 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_environment', '0010_sensor_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_before', models.ImageField(blank=True, null=True, upload_to='maintenance_images/before/')),
                ('image_after', models.ImageField(blank=True, null=True, upload_to='maintenance_images/after/')),
                ('action', models.CharField(choices=[('maintenance', 'Bảo trì'), ('replacement', 'Thay thế')], max_length=20)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Hủy bỏ')], default='pending', max_length=20)),
                ('moderator', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, choices=[('user', 'Người dùng'), ('Management', 'Người quản lí'), ('admin', 'Quản trị viên')], max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='monitor_environment.sensor')),
            ],
        ),
    ]
