# Generated by Django 5.0.13 on 2025-04-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_environment', '0011_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sensor_images/'),
        ),
    ]
