# Generated by Django 5.0.14 on 2025-05-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_environment', '0016_plantaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
